### ISSUE TITLE
Version 0.3

### ISSUE THREAD

**Issue by tjof2** [tjof2/pgure-svt#12]
- [X] HyperSpy demo with simple IPython notebook (#11) 
- [X] Hot-pixel filter for CCD camera data (#14) 
- [X] CMake installation option for library and executable (#15) 
- [X] Combine CMake and distutils for straightforward Python installation (#16)
- [X] Python wrapper to include error-checking on parameters and data (#17)
- [X] Fix noise estimation bug (#19)

_Aiming for April 30th._

**Comment by bm424** [comment]
Minimal IPython notebook in #11.

**Comment by tjof2** [comment]
Simple pixel-accuracy image registration using cross-correlation to account for sample drift (#21) can go in later update e.g. 0.3.1
