### ISSUE TITLE
PGURE-SVT v0.2

### ISSUE THREAD

**Issue by tjof2** [tjof2/pgure-svt#8]
Overhaul of much of the code to improve maintenance, as well as add new features and enhance performance on larger images.

The main change will be switching from standalone executable to a Python-wrapped library, thus removing need to maintain LibTIFF support and I/O functions, and easier parameter checking than currently. A compiled library can then be distributed with the next release.

**Task list**
- [X] Fix non-square images issue (#2) 
- [X] Improve performance for larger images (#3)
- [ ] Wrap the library for Python  (#5) 
- [ ] Remove standalone file I/O (#5)
- [ ] Check against code style guide (non-urgent)
- [ ] Basic documentation

**Comment by tjof2** [comment]
Closed as this will be worked on over time...
